#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/export-youtube-cookies.sh [BROWSER_SPEC] [OUTPUT_FILE]

Examples:
  scripts/export-youtube-cookies.sh chrome youtube-cookies.txt
  scripts/export-youtube-cookies.sh firefox:default-release youtube-cookies.txt
  scripts/export-youtube-cookies.sh 'chrome+GNOMEKEYRING:Default' youtube-cookies.txt

Environment:
  YTDLP_BIN   yt-dlp executable to use. Defaults to: yt-dlp
  TEST_URL    YouTube URL used to make yt-dlp load/save the jar.
              Defaults to yt-dlp's public test video.

The output is a Netscape cookie file containing only YouTube-related cookies.
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

browser_spec="${1:-chrome}"
output_file="${2:-youtube-cookies.txt}"
ytdlp_bin="${YTDLP_BIN:-yt-dlp}"
test_url="${TEST_URL:-https://www.youtube.com/watch?v=BaW_jenozKc}"

if ! command -v "$ytdlp_bin" >/dev/null 2>&1; then
  printf 'error: %s not found. Install yt-dlp or set YTDLP_BIN.\n' "$ytdlp_bin" >&2
  exit 1
fi

tmpdir="$(mktemp -d)"
raw_cookies="$tmpdir/all-cookies.txt"
filtered_cookies="$tmpdir/youtube-cookies.txt"

cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

printf 'Exporting cookies from browser with yt-dlp: %s\n' "$browser_spec" >&2

"$ytdlp_bin" \
  --cookies-from-browser "$browser_spec" \
  --cookies "$raw_cookies" \
  --skip-download \
  --no-warnings \
  "$test_url" >/dev/null

awk '
  BEGIN { FS = OFS = "\t" }

  /^# Netscape HTTP Cookie File/ { print; next }
  /^# This file is generated by yt-dlp\./ { print; next }
  /^$/ { print; next }
  /^#/ { next }

  NF >= 7 {
    domain = tolower($1)
    if (domain ~ /(^|\.)youtube\.com$/ \
        || domain ~ /(^|\.)youtube-nocookie\.com$/ \
        || domain ~ /(^|\.)googlevideo\.com$/) {
      print
    }
  }
' "$raw_cookies" > "$filtered_cookies"

cookie_count="$(awk 'BEGIN { count = 0 } /^[^#]/ && NF >= 7 { count++ } END { print count }' "$filtered_cookies")"

if [[ "$cookie_count" -eq 0 ]]; then
  printf 'error: no YouTube-related cookies were exported.\n' >&2
  printf 'Try another browser/profile, or log in to YouTube in that browser first.\n' >&2
  exit 1
fi

mv "$filtered_cookies" "$output_file"
chmod 600 "$output_file"

printf 'Wrote %s YouTube-related cookies to %s\n' "$cookie_count" "$output_file" >&2

if ! awk 'BEGIN { found = 0 } $6 == "LOGIN_INFO" { found = 1 } END { exit found ? 0 : 1 }' "$output_file"; then
  printf 'warning: LOGIN_INFO was not found; authenticated YouTube downloads may not work.\n' >&2
fi

if ! awk 'BEGIN { found = 0 } $6 == "SAPISID" || $6 == "__Secure-1PAPISID" || $6 == "__Secure-3PAPISID" { found = 1 } END { exit found ? 0 : 1 }' "$output_file"; then
  printf 'warning: no SAPISID/PAPISID cookie was found; authenticated YouTube downloads may not work.\n' >&2
fi
